version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      MOLAB_GATEWAY_HOST: backend  # Use the service name as the host
      MOLAB_GATEWAY_PORT: 8000

  worker:
    build: ./models/condmdi
    depends_on:
      - backend
    environment:
      MOLAB_GATEWAY_HOST: backend  # Use the service name as the host
      MOLAB_GATEWAY_PORT: 8000
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 2  # Number of workers to deploy
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]  # GPU required
              driver: nvidia

networks:
  app-network:
    driver: bridge
