version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  # frontend:
  #   build: ./frontend/export/html
  #   ports:
  #     - "8080:80"
  #   environment:  # TODO: This is not yet taken into account by Godot!
  #     GATEWAY_HOST: backend  # Use the service name as the host
  #     GATEWAY_PORT: 8000
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network

  worker:
    build: ./models/condmdi
    depends_on:
      - backend
    environment:
      GATEWAY_HOST: backend  # Use the service name as the host
      GATEWAY_PORT: 8000
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 2  # Number of workers to deploy
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]  # GPU required
              driver: nvidia

networks:
  app-network:
    driver: bridge
