version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network

  worker1:
    build: ./models/condmdi
    depends_on:
      - backend
    environment:
      GATEWAY_HOST: backend  # Use the service name as the host
      GATEWAY_PORT: 8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
