
############################################################
# ! Currently not in use
# TODO: Fleshen this out for system tests later on
############################################################

version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  condmdi:
    build: ./models/condmdi
    ports:
      - "5000:5000"
    depends_on:
      - backend

