site_name: MoLab
repo_url: https://github.com/JasonNero/MoLab
site_url: https://JasonNero.github.io/MoLab
site_description: Motion Lab - Human Motion Generation and Inbetweening
site_author: Jason Schuehlein
edit_uri: edit/main/docs/
repo_name: JasonNero/MoLab
copyright: Maintained by <a href="https://github.com/JasonNero">Jason Schuehlein</a>.

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - First Steps: getting-started/first-steps.md
  - User Guide:
    - Inference Parameters: usage/inference-parameters.md
    - MoLab Sequencer: usage/sequencer.md
    - MoLab Maya Plugin: usage/maya-plugin.md
  - API Reference:
    - Inference Worker: api-reference/inference-worker.md
    - WebSocket Worker: api-reference/websocket-worker.md
    - Backend: api-reference/backend.md
    - API Usage Example: api-reference/api-example.md
  - Concept: concept.md
  - Deployment Guide: deployment.md

plugins:
  - search
  - include-markdown
  - gh-admonitions
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: "google"

theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.indexes
    - navigation.tracking
    - content.code.annotate
    - toc.follow
    - navigation.footer
    - navigation.top
    - content.code.copy
    - content.tabs.link

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JasonNero/MoLab

markdown_extensions:
  - toc:
      permalink: true
      anchorlink: true
      anchorlink_class: "toclink"
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
  - pymdownx.magiclink:
  - attr_list:
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
  - markdown.extensions.attr_list:
  - pymdownx.keys:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true

